language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: COMPOSER_EXTRAS='symfony/event-dispatcher ^3.4 symfony/contracts ^2.0'
    - php: 7.3
    - php: 7.4
    - php: 7.4
      env: DEPENDENCIES='dev'
  allow_failures:
    - env: DEPENDENCIES='dev'
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ -n "$COMPOSER_EXTRAS" ]; then composer require $COMPOSER_EXTRAS --no-update; fi;
  - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
  - composer update $COMPOSER_FLAGS

script:
   - bin/phpspec run --format=dot
   - ./vendor/bin/phpunit -v
   - ./vendor/bin/behat --format=progress
   - composer config platform.php 7.3.0
   - ln -s `which composer` composer.phar
   - make phpspec.phar

deploy:
  provider: releases
  api_key:
    secure: eTlXM76IvH1Ws57gtBi5Q7trQ3rEXjt+7wOH4HLw6WhhywMF4THMuQQC0j5DhWtiLJlVYHaIfNbapbG+DVUqyXZZA+aXQSuh9aNM1fbkEShbWFpOrCd+Y3I1lXNvOcGZ5hvJieDVgWSc0osNLCQzaza17fhYUtbKsj4Qwc5ek8k=
  file: phpspec.phar
  skip_cleanup: true
  on:
    tags: true
    condition: DEPLOY_PHAR == "yes"
